export interface GameCard {
  id: string;
  name: string;
  description: string;
  price: number;
  actions: number;
  buys: number;
  defense: number;
  damage: number;
  trash: number;
  credits: number;
  cards: number;
  impedes: number;
  type: CardType;
  available: number;
}

export type CardType = `strategy` | `resource` | `impeded`;

export const strategyCards: GameCard[] = [
  {
    id: `counter-espionage`,
    type: `strategy`,
    name: `Counter Espionage (2 actions, 2 impede)`,
    price: 300,
    actions: 2,
    impedes: 2,
    description: `Allow the player to play 2 more strategy cards and add 2 Impeded cards (from the supply) to their opponents discard pile.`,
    buys: 0,
    defense: 0,
    damage: 0,
    trash: 0,
    credits: 0,
    cards: 0,
    available: 10,
  },
  {
    id: `preemptive-intelligence`,
    type: `strategy`,
    name: `Preemptive Intelligence (2 actions, 1 card)`,
    price: 300,
    actions: 2,
    cards: 1,
    description: `Allow the player to draw an additional card from their deck and play 2 more strategy cards.`,
    buys: 0,
    defense: 0,
    damage: 0,
    trash: 0,
    credits: 0,
    impedes: 0,
    available: 10,
  },
  {
    id: `aggressive-acquisition`,
    type: `strategy`,
    name: `Aggressive Acquisition (2 actions, 1 buy)`,
    price: 300,
    actions: 2,
    buys: 1,
    description: `Allow the player to play 2 more strategy cards and lets them buy an additional card during their buy phase.`,
    defense: 0,
    damage: 0,
    trash: 0,
    credits: 0,
    cards: 0,
    impedes: 0,
    available: 10,
  },
  {
    id: `defensive-maneuver`,
    type: `strategy`,
    name: `Defensive Maneuver (1 defense, 1 action)`,
    price: 300,
    defense: 1,
    actions: 1,
    description: `Allow the player to play 1 more strategy card and also adds 1 defense during the combat phase.`,
    buys: 0,
    damage: 0,
    trash: 0,
    credits: 0,
    cards: 0,
    impedes: 0,
    available: 10,
  },
  {
    id: `trade-negotiations`,
    type: `strategy`,
    name: `Trade Negotiations (200 credits, 1 buy)`,
    price: 400,
    credits: 200,
    buys: 1,
    description: `The player gains 200 more credits and can buy an additional card during their buy phase.`,
    defense: 0,
    damage: 0,
    trash: 0,
    cards: 0,
    impedes: 0,
    actions: 0,
    available: 10,
  },
  {
    id: `technology-investment`,
    type: `strategy`,
    name: `Technology Investment (2 defense, 2 trash)`,
    price: 500,
    defense: 2,
    buys: 0,
    description: `Adds 2 defense during the combat phase and allows the player to trash 2 cards from their hand during their cleanup phase.`,
    damage: 0,
    trash: 2,
    credits: 0,
    cards: 0,
    impedes: 0,
    actions: 0,
    available: 10,
  },
  {
    id: `braintrust-accumulation`,
    type: `strategy`,
    name: `Braintrust Accumulation (3 cards)`,
    price: 400,
    cards: 3,
    description: `Allow the player to immediately draw 3 cards from their deck.`,
    defense: 0,
    damage: 0,
    trash: 0,
    credits: 0,
    impedes: 0,
    actions: 0,
    buys: 0,
    available: 10,
  },
  {
    id: `impose-tariffs`,
    type: `strategy`,
    name: `Impose Tariffs (200 credits, 1 card, 1 buy)`,
    price: 500,
    credits: 200,
    cards: 1,
    buys: 1,
    description: `Allow the player to immediately draw 1 card from their deck then they gain 200 more credits and can buy an additional card during their buy phase.`,
    defense: 0,
    damage: 0,
    trash: 0,
    impedes: 0,
    actions: 0,
    available: 10,
  },
  {
    id: `precision-strike`,
    type: `strategy`,
    name: `Precision Strike (1 damage, 1 trash)`,
    price: 600,
    damage: 1,
    trash: 1,
    description: `Allow the player to trash 1 card from their hand during their cleanup phase and deals 1 damage during the combat phase.`,
    defense: 0,
    credits: 0,
    cards: 0,
    impedes: 0,
    actions: 0,
    buys: 0,
    available: 10,
  },
  {
    id: `critical-hit`,
    type: `strategy`,
    name: `Critical Hit (3 damage, 1 card)`,
    price: 800,
    damage: 3,
    trash: 0,
    description: `Allow the player to immediately draw 1 card from their deck and deals 3 damage during the combat phase.`,
    defense: 0,
    credits: 0,
    cards: 1,
    impedes: 0,
    actions: 0,
    buys: 0,
    available: 10,
  },
];

export const resourceCards: GameCard[] = [
  {
    id: `hydrogen`,
    type: `resource`,
    name: `Hydrogen 100`,
    price: 0,
    credits: 100,
    description: `Can be spent for 100 credits. Also if you have less health than your opponent you may discard all of your Hydrogen cards in hand and redraw that many cards`,
    actions: 0,
    buys: 0,
    defense: 0,
    damage: 0,
    trash: 0,
    cards: 0,
    impedes: 0,
    available: 10,
  },
  {
    id: `oxygen`,
    type: `resource`,
    name: `Oxygen 200`,
    price: 300,
    credits: 200,
    description: `Can be spent for 200 credits.`,
    actions: 0,
    buys: 0,
    defense: 0,
    damage: 0,
    trash: 0,
    cards: 0,
    impedes: 0,
    available: 10,
  },
  {
    id: `carbon`,
    type: `resource`,
    name: `Carbon 300`,
    price: 600,
    credits: 300,
    description: `Can be spent for 300 credits.`,
    actions: 0,
    buys: 0,
    defense: 0,
    damage: 0,
    trash: 0,
    cards: 0,
    impedes: 0,
    available: 10,
  },
];

export const impededCards: GameCard[] = [
  {
    id: `impeded`,
    type: `impeded`,
    name: `Impeded`,
    price: 0,
    credits: 0,
    description: `Impeded cards have no use in the game. They represent setbacks the players face when trying to achieve their goals. They cannot be played or discarded during the strategy or buy phase. They can only be trashed or discarded during the cleanup phase.`,
    actions: 0,
    buys: 0,
    defense: 0,
    damage: 0,
    trash: 0,
    cards: 0,
    impedes: 0,
    available: 10,
  },
];